#默认镜像源地址
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '10.0'

workspace 'BLEMidAutumn.xcworkspace'

target :AutumnTest do
 project 'AutumnTest/AutumnTest.xcodeproj'
 pod 'SVProgressHUD', '~> 2.0.3'
 pod 'Masonry'
 pod 'ReactiveCocoa', '~> 2.5'
 pod 'DateTools', '~> 2.0.0'
 pod 'Protobuf'
 pod 'iOSDFULibrary'
 pod 'IVBaseKit', '~> 1.3.8'
 pod 'BLEMidAutumn', '~> 6.6.4'
# pod 'BLE3Framework', '~> 5.1.0'

end


